apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: ryzen28/mongo:latest
          args:
            - "--bind_ip=0.0.0.0"
          env:
            - name: MONGO_DB_DATABASE
              value: admin
            - name: MONGO_DB_USERNAME
              value: admin
            - name: MONGO_DB_PASSWORD
              value: admin
            - name: MONGO_ROOT_PASSWORD
              value: "admin"
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
