apiVersion: v1
kind: Pod
metadata:
  name: mongo-express
  labels:
    app: mongo-express
    tier: backend
spec:
  containers:
    - name: mongo-express
      image: ryzen28/mongo-express:latest
      ports:
        - containerPort: 8081
      env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongo-service
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: admin
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: admin
        - name: MONGO_URL
          value: "mongodb://admin:admin@mongo-service:27017"
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  labels:
    app: mongo-express
    tier: backend
spec:
  type: NodePort
  selector:
    app: mongo-express
    tier: backend
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30025
